parameters:
  - name: veracode-api-id
    #displayName: veracode-api-id
    default: ""
    type: string
  - name: veracode-api-key
    #displayName: veracode-api-key
    default: ""
    type: string
  - name: applicationName
    # displayName: "Application Name"
    default: ""
    type: string
  - name: sandboxName
    #displayName: "Sandbox Name"
    default: "Release Candidate"
    type: string

jobs:
  - job: SAST_Release_Candidate_Promote
    displayName: Promotion of a Sandbox to Policy
    
    variables:
      - name: ApplicationId
      - name: SandboxId
      - name: AnalysisId
      - name: AnalysisName
      - name: resultsReady
        value: "false"
    
    steps:
    - script: java --version
      continueOnError: true
      displayName: Report Java Version installed

    - pwsh: |
        $versionstring = curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | Out-String -Stream | Select-String -Pattern 'latest';
        $wrapper_version = $versionstring -replace '\s','' -replace '<latest>','' -replace '</latest>','';
        echo "Pulling down wrapper version: $wrapper_version"
        curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION-dist.zip -o $(Build.ArtifactStagingDirectory)/dist.zip
        7z e $(Build.ArtifactStagingDirectory)/dist.zip -o$(Build.ArtifactStagingDirectory)/extract/ -y
      displayName: Downloading the latest version of the Veracode Java API
      enabled: true

    - script: ls -la $(Build.ArtifactStagingDirectory)
      displayName: Show Artifact Directory Content

    - script: |
        ls -la $(Build.ArtifactStagingDirectory)/extract/
      displayName: Show Extract Directory Content
      enabled: true

    - script: |
        java -jar $(Build.ArtifactStagingDirectory)/extract/VeracodeJavaAPI.jar -version
      displayName: Veracode Wrapper Version
      enabled: false

 
