parameters:
  - name: quickScan
    displayName: Quick Scan
    type: boolean
    default: false
    values: 
      - true
      - false

vmImage: ubuntu-latest

jobs:
  - job: SCA_Agent_Security_Testing
    displayName: Software Componsition Analysis Testing

    steps:
    - script: ls -la $(Build.SourcesDirectory)
    - ${{ if eq(parameters.quickScan, true) }}:
      - script: curl -sSL  https://download.sourceclear.com/ci.sh | sh -s -- scan $(Build.SourcesDirectory) --quick --ws $(WORKSPACE_SLUG)
        displayName: Performing SCA Analysis
    - ${{ if eq(parameters.quickScan, false) }}:
      - script: curl -sSL  https://download.sourceclear.com/ci.sh | sh -s -- scan $(Build.SourcesDirectory) --ws $(WORKSPACE_SLUG)
        displayName: Performing SCA Analysis
