parameters:
  - name: veracode-api-id
    #displayName: veracode-api-id
    default: ""
    type: string
  - name: veracode-api-key
    #displayName: veracode-api-key
    default: ""
    type: string
  - name: applicationName
    # displayName: "Application Name"
    default: ""
    type: string
  - name: sandboxName
    #displayName: "Sandbox Name"
    default: "Release Candidate"
    type: string

jobs:
  - job: SAST_Release_Candidate_Promote
    displayName: Promotion of $(applicationName) $(sandboxName)
    
    steps:
    - script: | 
        echo 'Hello World'
