# File: veracode-sast-pipeline-job.yml

parameters:
  - name: veracode-api-id
    default: ""
    type: string
  - name: veracode-api-key
    default: ""
    type: string
  - name: downloadArtifact
    default: ""
    type: string
    
jobs:
  - job: SAST_Security_Testing
    displayName: Static Analysis Security Testing
    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
        inputs:
          artifact: ${{ parameters.downloadArtifact }}

    - script: ls -la $(Agent.BuildDirectory)
    - script: ls -la $(Build.StagingDirectory)
      displayName: "Show Workspace Contents"

    - script: echo 'Prepare Veracode Pipeline SAST'
    - script: curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      displayName: "Download Pipeline Scan"

    - script: unzip -o pipeline-scan-LATEST.zip
      displayName: "Unzip Pipeline Scan"

    - script: java -jar pipeline-scan.jar --version
      displayName: "Pipeline Scan Version" 

     - script: java -jar pipeline-scan.jar -vid ${{ parameters.veracode-api-id }} -vkey ${{ parameters.veracode-api-key }} -f $(Build.StagingDirectory)\$(system.teamProject).zip  # || true
       displayName: "Running Analysis"
